##1st Problem

In [3]:
import numpy as np
arr = np.random.randint(0,100,10)
print(arr)
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))

[67 84 86 64 51 98 73 92 70 68]
98
51
75.3


Problem 2

In [7]:
arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])
print(arr[arr > 50])
print(np.sort(arr))
print(np.argmax(arr))

[60 55 90 75]
[30 40 45 50 55 60 75 90]
4


Problem 3

In [13]:
temp = np.random.randint(20,40,16).reshape(4,4)
print(temp)
print(np.mean(temp,axis = 1))
print(np.max(temp))
temp[temp > 35] = 35
print(temp)

[[37 29 28 23]
 [37 30 32 29]
 [30 25 29 27]
 [28 34 29 37]]
[29.25 32.   27.75 32.  ]
37
[[35 29 28 23]
 [35 30 32 29]
 [30 25 29 27]
 [28 34 29 35]]


Problem 4

In [8]:
traffic = np.random.randint(0,50,15).reshape(3,5)
print(traffic)
print("Total Car per intersection",np.sum(traffic,axis=0))
print("Total cars per time slot",np.sum(traffic,axis = 1))

[[33 47 34 19  4]
 [46  7 15 42 41]
 [34 49 49 23 34]]
Total Car per intersection [113 103  98  84  79]
Total cars per time slot [137 151 189]


Problem 5

In [11]:
stock = np.array([12, 15, 9, 20, 18])
stock += 5
stock = stock -  (stock*0.1)
print(stock)

[15.3 18.  12.6 22.5 20.7]


Pandas

Problem 1

In [12]:
import pandas as pd
data = {
 	'Name': ['Rahim', 'Karim', 'Selina', 'Babul', 'Mitu'],
 	'Math': [88, 75, 95, 60, 80],
 	'English': [78, 85, 90, 70, 88],
 	'Science': [92, 70, 85, 65, 90]
}
df = pd.DataFrame(data)
print(df.head(3))
print(df.columns)
print(df.index)

     Name  Math  English  Science
0   Rahim    88       78       92
1   Karim    75       85       70
2  Selina    95       90       85
Index(['Name', 'Math', 'English', 'Science'], dtype='object')
RangeIndex(start=0, stop=5, step=1)


Problem 2

In [16]:
data = {
 	'Product': ['Phone', 'Laptop', 'Tablet', 'Monitor', 'Mouse'],
 	'Price': [700, 1200, 300, 250, 50],
 	'Units_Sold': [10, 5, 8, 6, 20]
 }
df = pd.DataFrame(data)
print(df[["Product","Price"]])
print(df.loc[2])
print(df.iloc[2])

df["revenue"] = df["Price"]*df["Units_Sold"]
print(df.sort_values(by = "revenue",ascending= False))

   Product  Price
0    Phone    700
1   Laptop   1200
2   Tablet    300
3  Monitor    250
4    Mouse     50
Product       Tablet
Price            300
Units_Sold         8
Name: 2, dtype: object
Product       Tablet
Price            300
Units_Sold         8
Name: 2, dtype: object
   Product  Price  Units_Sold  revenue
0    Phone    700          10     7000
1   Laptop   1200           5     6000
2   Tablet    300           8     2400
3  Monitor    250           6     1500
4    Mouse     50          20     1000


Problem 3

In [19]:
data = {
 	'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],
 	'Days_Present': [20, 18, 22, 15, 25],
 	'Days_Absent': [2, 4, 1, 7, 0]
 }
df = pd.DataFrame(data)
df.set_index("Student",inplace=True)
print(df)
print(df.drop(columns="Days_Absent"))
# print(df)

         Days_Present  Days_Absent
Student                           
Amin               20            2
Tina               18            4
Rafi               22            1
Nadia              15            7
Sabbir             25            0
         Days_Present
Student              
Amin               20
Tina               18
Rafi               22
Nadia              15
Sabbir             25


Problem 4

In [20]:
data = {
 	'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],
 	'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],
 	'Salary': [40000, 55000, 52000, 45000, 47000],
 	'Experience': [2, 5, 4, 3, 6]
 }
df = pd.DataFrame(data)
print(df[df["Salary"] > 45000])
print(df[df["Department"] == "IT"])
print(df[(df["Salary"] > 45000) & (df["Experience"] > 3)])
print(df.sort_values(by = "Experience"))

    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6
    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6
    Name Department  Salary  Experience
0  Rafiq         HR   40000           2
3   Rima      Sales   45000           3
2  Tuhin         IT   52000           4
1  Nadia         IT   55000           5
4  Faruk      Sales   47000           6


Problem 5

In [31]:
data = {
 	'City': ['Dhaka', 'Sylhet', 'Chittagong', 'Rajshahi', 'Khulna'],
 	'Temp': [32, 28, 30, 35, 33],
 	'Humidity': [60, 75, 70, 55, 65]
 }
df = pd.DataFrame(data)
print(df[df["Temp"] > 33])
print(df.sort_values(by = "Temp",ascending= False))
print(df.loc[df["Humidity"] == df['Humidity'].max(),"City"])

       City  Temp  Humidity
3  Rajshahi    35        55
         City  Temp  Humidity
3    Rajshahi    35        55
4      Khulna    33        65
0       Dhaka    32        60
2  Chittagong    30        70
1      Sylhet    28        75
1    Sylhet
Name: City, dtype: object
