In [ ]:
import numpy as np
a = np.zeros((3,3))
b = np.ones((2,5))
c = np.full((2,3),7)
print(a)
print(b)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]]


In [4]:
d = np.arange(10,51,2)
print(d)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [10]:
e = np.arange(0,16).reshape(4,4)
first_row = e[:1,::]
last_column = e[::,3:4]
print(e)
print(first_row)
print(last_column)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [ ]:
d_array = np.array([1,2,3])
tt_m = np.random.randint(1,10,9).reshape(3,3)
print(d_array)
print()
print(tt_m)
ans = d_array + tt_m
print(ans)

[1 2 3]

[[3 6 4]
 [5 8 1]
 [7 2 5]]
[[ 4  8  7]
 [ 6 10  4]
 [ 8  4  8]]


In [21]:
a = np.array([4,23,5,4,3,6,1])
b = np.array([4,3,2,5,6,23,1])
print((a+b)/2)
print(a**2 + b**2)


[ 4.  13.   3.5  4.5  4.5 14.5  1. ]
[ 32 538  29  41  45 565   2]
